### ISSUE TITLE
ch7.mutex - compilaion failed

### ISSUE THREAD

**Issue by ghost** [oysstu/pyopencl-in-action#4]
```
(cl) ~/work/p1/pyopencl-in-action$ python -m "ch7.mutex"
Using CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
On platform: Experimental OpenCL 2.1 CPU Only Platform (OpenCL 2.1 LINUX)

Build log:
/home/ubuntu/work/p1/pyopencl-in-action/ch7/mutex.py:46: UserWarning: Pre-build attribute access defeats compiler caching.
  print(prog.get_build_info(dev, cl.program_build_info.LOG))

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/work/p1/pyopencl-in-action/ch7/mutex.py", line 43, in <module>
    prog.build(options=['-Werror'], devices=[dev])
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/pyopencl/__init__.py", line 510, in build
    options_bytes=options_bytes, source=self._source)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/pyopencl/__init__.py", line 554, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz' on 'Experimental OpenCL 2.1 CPU Only Platform' at 0xdbd158>:

Compilation started
1:2:26: error: OpenCL extension 'cl_khr_global_int32_base_atomics' is core feature or supported optional core feature - ignoring
#pragma OPENCL EXTENSION cl_khr_global_int32_base_atomics : enable
                         ^
Compilation failed

(options: -Werror -I /home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/pyopencl/cl)
(source saved as /tmp/tmpqm5dqjib.cl)

```

```

(cl) ~/work/p1/pyopencl-in-action$ python -m "ch11.string_search"
Using GPU: Intel(R) Gen9 HD Graphics NEO
On platform: Intel(R) OpenCL HD Graphics (OpenCL 2.1)

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/work/p1/pyopencl-in-action/ch11/string_search.py", line 84, in <module>
    with open(TEXT_FILE, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'kafka.txt'
(cl) ~/work/p1/pyopencl-in-action$ 

```

**Comment by oysstu** [comment]
I have no idea why the first one fails. I get the following output
```
Using CPU: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
On platform: Intel(R) CPU Runtime for OpenCL(TM) Applications (OpenCL 2.1 LINUX)

/usr/lib/python3.7/site-packages/pyopencl/cffi_cl.py:1517: CompilerWarning: From-source build succeeded, but resulted in non-empty logs:
Build on <pyopencl.Device 'Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz' on 'Intel(R) CPU Runtime for OpenCL(TM) Applications' at 0x5637977efe08> succeeded, but said:

Compilation started
Compilation done
Linking started
Linking done
Device build started
Device build done
Kernel <mutex> was not vectorized
Done.
  warn(text, CompilerWarning)
Sum: [4]
```
I see you're using the experimental opencl 2.1 drivers, could be something related to that.

**Comment by ghost** [comment]
I see - I do not want to use experimental. I have available those 
 
```
<pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x556d29d9a370>
<pyopencl.Platform 'Experimental OpenCL 2.1 CPU Only Platform' at 0x556d299366d0>

```

but on "ch11.string_search" it fails where HD Graphics is used

```
(cl) ~/work/p1/pyopencl-in-action$ python -m "ch11.string_search"
Using GPU: Intel(R) Gen9 HD Graphics NEO
On platform: Intel(R) OpenCL HD Graphics (OpenCL 2.1)

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/work/p1/pyopencl-in-action/ch11/string_search.py", line 84, in <module>
    with open(TEXT_FILE, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'kafka.txt'

```

**Comment by oysstu** [comment]
That is a separate issue. It tries to open ch11/kafka.txt. I've pushed a new version that handles the path better, try that

**Comment by ghost** [comment]
after update - it works _ch11.string_search_

```
(cl) ~/work/p1/pyopencl-in-action$ python -m "ch11.string_search"
Using GPU: Intel(R) Gen9 HD Graphics NEO
On platform: Intel(R) OpenCL HD Graphics (OpenCL 2.1)

Number of occurrences of 'that': 330
Number of occurrences of 'with': 237
Number of occurrences of 'have': 110
Number of occurrences of 'from': 116

```
