### ISSUE TITLE
Issue on interp_image no 'input_car.png'

### ISSUE THREAD

**Issue by ghost** [oysstu/pyopencl-in-action#5]
```
(cl) ~/work/p1/pyopencl-in-action$ python -m "ch6.interp_image"
Using GPU: Intel(R) Gen9 HD Graphics NEO
On platform: Intel(R) OpenCL HD Graphics (OpenCL 2.1)

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/work/p1/pyopencl-in-action/ch6/interp_image.py", line 64, in <module>
    im_src = imread('input_car.png').astype(dtype=np.uint16)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/skimage/io/_io.py", line 62, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 214, in call_plugin
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'input_car.png'

```

requesting 'input_car.png' file even it's in directory?

**Comment by oysstu** [comment]
Same issue as with kafka.txt. Fixed now
