### ISSUE TITLE
mutex Compilation failed

### ISSUE THREAD

**Issue by ghost** [oysstu/pyopencl-in-action#6]
```
cl) ~/work/p1/pyopencl-in-action$ python -m "ch7.mutex"
Using CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
On platform: Experimental OpenCL 2.1 CPU Only Platform (OpenCL 2.1 LINUX)

Build log:
/home/ubuntu/work/p1/pyopencl-in-action/ch7/mutex.py:46: UserWarning: Pre-build attribute access defeats compiler caching.
  print(prog.get_build_info(dev, cl.program_build_info.LOG))

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/work/p1/pyopencl-in-action/ch7/mutex.py", line 43, in <module>
    prog.build(options=['-Werror'], devices=[dev])
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/pyopencl/__init__.py", line 510, in build
    options_bytes=options_bytes, source=self._source)
  File "/home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/pyopencl/__init__.py", line 554, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz' on 'Experimental OpenCL 2.1 CPU Only Platform' at 0x21eee78>:

Compilation started
1:2:26: error: OpenCL extension 'cl_khr_global_int32_base_atomics' is core feature or supported optional core feature - ignoring
#pragma OPENCL EXTENSION cl_khr_global_int32_base_atomics : enable
                         ^
Compilation failed

(options: -Werror -I /home/ubuntu/anaconda3/envs/cl/lib/python3.6/site-packages/pyopencl/cl)
(source saved as /tmp/tmpvkn4udlr.cl)

```

**Comment by oysstu** [comment]
I've tested this both on intel haswell (i5-4670K) and skylake (i7-6700), and both works with
`Intel(R) CPU Runtime for OpenCL(TM) Applications (OpenCL 2.1 LINUX)`

I suggest that you take this up with pyopencl/opencl devs if this feature is important to you. I'm still leaning towards a problem with your installed CPU opencl driver
